import { SelectionNode, ListValueNode, EnumValueNode, NullValueNode, BooleanValueNode, StringValueNode, FloatValueNode, IntValueNode, ValueNode, VariableNode, FieldNode, FragmentSpreadNode, InlineFragmentNode } from "graphql";
export declare function isFieldNode(obj: SelectionNode): obj is FieldNode;
export declare function isFragmentSpreadNode(obj: SelectionNode): obj is FragmentSpreadNode;
export declare function isInlineFragmentNode(obj: SelectionNode): obj is InlineFragmentNode;
export declare function isVariableNode(obj: ValueNode): obj is VariableNode;
export declare function isIntValueNode(obj: ValueNode): obj is IntValueNode;
export declare function isFloatValueNode(obj: ValueNode): obj is FloatValueNode;
export declare function isStringValueNode(obj: ValueNode): obj is StringValueNode;
export declare function isBooleanValueNode(obj: ValueNode): obj is BooleanValueNode;
export declare function isNullValueNode(obj: ValueNode): obj is NullValueNode;
export declare function isEnumValueNode(obj: ValueNode): obj is EnumValueNode;
export declare function isListValueNode(obj: ValueNode): obj is ListValueNode;
export declare function isObjectValueNode(obj: ValueNode): obj is ListValueNode;
